dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
install:
  - npm i
  - pip install awscli --upgrade --user

stages:
  - build
jobs:
  include:
    - stage: build
      name: Build
      if: branch =~ master$
      script:
        - npm run build
    - stage: deploy
      name: deploy
      if: branch =~ master$
      script:
        - aws s3 cp ./dist s3://alienhunt.sheaclose.com
    - stage: deploy
      name: deploy
      if: branch =~ master$
      script:
        - aws cloudfront create-invalidation --distribution-id E2BD1PN7KPPA5P --paths /*
